# Generated by Django 4.0.5 on 2022-07-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=500, max_length=127),
            preserve_default=False,
        ),
    ]
